version = 3
final_space = true

[palette]
  blue = '#00afb9'
  lavender = '#00afb9'
  os = '#ACB0BE'
  pink = '#fdfcdc'
  orange = '#fed9b7'
  text = '#1b263b'
  wight = '#FFFFFF'
  cement = '#f07167'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    #leading_diamond = ''
    leading_diamond = ''
    template = '{{.Icon}} '
    foreground = 'p:wight'
    #powerline_symbol = ''
    powerline_symbol = ''
    background = 'p:blue'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }}'
    foreground = 'p:text'
    #powerline_symbol = ''
    powerline_symbol = ''
    background = 'p:blue'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:text'
    #powerline_symbol = ''
    powerline_symbol = ''
    background = 'p:pink'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ end }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:orange'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = "files"
      fetch_virtual_env = true
      fetch_version = true
      python_icon = "🐍"


  [[blocks.segments]]
    template = ' {{ .HEAD }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:cement'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '
