---
cluster_name: Kubernetes-VBox-Cluster
network:
  dns_servers:
    - 9.9.9.11
    - 1.1.1.1
  pod_cidr: 10.244.0.0/16
  service_cidr: 10.96.0.0/12
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 2
    cpu: 2
    memory: 4096
software:
  box: bento/ubuntu-24.04
  calico: 3.28.2
  kubernetes: v1.30.0
  os: xUbuntu_22.04
  crio: v1.30.0
vm_options:
  vbox_guest_additions: true
  enable_hyperv_features: true
  enable_nested_virtualization: true
