cluster_name: Kubernetes-VBox-Cluster

network:
  pod_cidr: 10.244.0.0/16
  service_cidr: 10.96.0.0/12
  control_ip: 192.168.1.100
  worker_ip_prefix: 192.168.1
  private_ip_prefix: 172.16.0
  dns_servers: "9.9.9.9,1.1.1.1"

nodes:
  control:
    cpu: 4
    memory: 6144
  workers:
    count: 2
    cpu: 4
    memory: 6144

software:
  box: bento/ubuntu-24.04
  calico: 3.30.0
  kubernetes: v1.34
  os: xUbuntu_24.04
  crio: v1.33
